# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: Default

variables:
- name: release_destination
  value: Self_host_agent_test.AzureDevOps-HostAgent01
- name: script_dir
  value: /home/azureuser/deploy/

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - script: |
        gcc helloc.c -o hello
        mkdir -p '$(script_dir)'
        cp -p hello '$(script_dir)'
      displayName: 'Build C Program'
    - task: CopyFilesOverSSH@0
      inputs:
        sshEndpoint: 'Deploy-Distination'
        sourceFolder: '$(script_dir)'
        contents: '**'
        targetFolder: '/home/azureuser/deploy/'